#########################
# ISCO08 code generator #
#########################

## Adapted from occupar package by Diogo Ferrari
## https://github.com/DiogoFerrari/occupar
ISSP5 <- ISSP5 %>%
  dplyr::mutate(
      ISCO08_code = dplyr::case_when(
                                             ISCO08 == "Armed forces occupations" ~ 0000,
                                             ISCO08 == "Armed forces occupations" ~ 0010,
                                             ISCO08 == "Commissioned armed forces officers" ~ 0100,
                                             ISCO08 == "Commissioned armed forces officers" ~ 0110,
                                             ISCO08 == "Non-commissioned armed forces officers" ~ 0200,
                                             ISCO08 == "Non-commissioned armed forces officers" ~ 0210,
                                             ISCO08 == "Armed forces occupations, other ranks" ~ 0300,
                                             ISCO08 == "Armed forces occupations, other ranks" ~ 0310,
                                             ISCO08 == "Managers" ~ 1000,
                                             ISCO08 == "Chief executives, senior officials and legislators" ~ 1100,
                                             ISCO08 == "Legislators and senior officials" ~ 1110,
                                             ISCO08 == "Legislators" ~ 1111,
                                             ISCO08 == "Senior government officials" ~ 1112,
                                             ISCO08 == "Traditional chiefs and heads of village" ~ 1113,
                                             ISCO08 == "Senior officials of special-interest organizations" ~ 1114,
                                             ISCO08 == "Managing directors and chief executives" ~ 1120,
                                             ISCO08 == "Administrative and commercial managers" ~ 1200,
                                             ISCO08 == "Business services and administration managers" ~ 1210,
                                             ISCO08 == "Finance managers" ~ 1211,
                                             ISCO08 == "Human resource managers" ~ 1212,
                                             ISCO08 == "Policy and planning managers" ~ 1213,
                                             ISCO08 == "Business services and administration managers not elsewhere classified" ~ 1219,
                                             ISCO08 == "Sales, marketing and development managers" ~ 1220,
                                             ISCO08 == "Sales and marketing managers" ~ 1221,
                                             ISCO08 == "Advertising and public relations managers" ~ 1222,
                                             ISCO08 == "Research and development managers" ~ 1223,
                                             ISCO08 == "Production and specialized services managers" ~ 1300,
                                             ISCO08 == "Production managers in agriculture, forestry and fisheries" ~ 1310,
                                             ISCO08 == "Agricultural and forestry production managers" ~ 1311,
                                             ISCO08 == "Aquaculture and fisheries production managers" ~ 1312,
                                             ISCO08 == "Manufacture, mining, construction, distribution managers" ~ 1320,
                                             ISCO08 == "Manufacturing managers" ~ 1321,
                                             ISCO08 == "Mining managers" ~ 1322,
                                             ISCO08 == "Construction managers" ~ 1323,
                                             ISCO08 == "Supply, distribution and related managers" ~ 1324,
                                             ISCO08 == "ICT service managers" ~ 1330,
                                             ISCO08 == "Professional services managers" ~ 1340,
                                             ISCO08 == "Child care services managers" ~ 1341,
                                             ISCO08 == "Health services managers" ~ 1342,
                                             ISCO08 == "Aged care services managers" ~ 1343,
                                             ISCO08 == "Social welfare managers" ~ 1344,
                                             ISCO08 == "Education managers" ~ 1345,
                                             ISCO08 == "Financial and insurance services branch managers" ~ 1346,
                                             ISCO08 == "Professional services managers not elsewhere classified" ~ 1349,
                                             ISCO08 == "Hospitality, retail and other services managers" ~ 1400,
                                             ISCO08 == "Hotel and restaurant managers" ~ 1410,
                                             ISCO08 == "Hotel managers" ~ 1411,
                                             ISCO08 == "Restaurant managers" ~ 1412,
                                             ISCO08 == "Retail and wholesale trade managers" ~ 1420,
                                             ISCO08 == "Other services managers" ~ 1430,
                                             ISCO08 == "Sports, recreation and cultural centre managers" ~ 1431,
                                             ISCO08 == "Services managers not elsewhere classified" ~ 1439,
                                             ISCO08 == "Professionals" ~ 2000,
                                             ISCO08 == "Science and engineering professionals" ~ 2100,
                                             ISCO08 == "Physical and earth science professionals" ~ 2110,
                                             ISCO08 == "Physicists and astronomers" ~ 2111,
                                             ISCO08 == "Meteorologists" ~ 2112,
                                             ISCO08 == "Chemists" ~ 2113,
                                             ISCO08 == "Geologists and geophysicists" ~ 2114,
                                             ISCO08 == "Mathematicians, actuaries and statisticians" ~ 2120,
                                             ISCO08 == "Life science professionals" ~ 2130,
                                             ISCO08 == "Biologists, botanists, zoologists and related professionals" ~ 2131,
                                             ISCO08 == "Farming, forestry and fisheries advisers" ~ 2132,
                                             ISCO08 == "Environmental protection professionals" ~ 2133,
                                             ISCO08 == "Engineering professionals (excluding electrotechnology)" ~ 2140,
                                             ISCO08 == "Industrial and production engineers" ~ 2141,
                                             ISCO08 == "Civil engineers" ~ 2142,
                                             ISCO08 == "Environmental engineers" ~ 2143,
                                             ISCO08 == "Mechanical engineers" ~ 2144,
                                             ISCO08 == "Chemical engineers" ~ 2145,
                                             ISCO08 == "Mining engineers, metallurgists and related professionals" ~ 2146,
                                             ISCO08 == "Engineering professionals not elsewhere classified" ~ 2149,
                                             ISCO08 == "Electrotechnology engineers" ~ 2150,
                                             ISCO08 == "Electrical engineers" ~ 2151,
                                             ISCO08 == "Electronics engineers" ~ 2152,
                                             ISCO08 == "Telecommunications engineers" ~ 2153,
                                             ISCO08 == "Architects, planners, surveyors and designers" ~ 2160,
                                             ISCO08 == "Building architects" ~ 2161,
                                             ISCO08 == "Landscape architects" ~ 2162,
                                             ISCO08 == "Product and garment designers" ~ 2163,
                                             ISCO08 == "Town and traffic planners" ~ 2164,
                                             ISCO08 == "Cartographers and surveyors" ~ 2165,
                                             ISCO08 == "Graphic and multimedia designers" ~ 2166,
                                             ISCO08 == "Health professionals" ~ 2200,
                                             ISCO08 == "Medical doctors" ~ 2210,
                                             ISCO08 == "Generalist medical practitioners" ~ 2211,
                                             ISCO08 == "Specialist medical practitioners" ~ 2212,
                                             ISCO08 == "Nursing and midwifery professionals" ~ 2220,
                                             ISCO08 == "Nursing professionals" ~ 2221,
                                             ISCO08 == "Midwifery professionals" ~ 2222,
                                             ISCO08 == "Traditional and complementary medicine professionals" ~ 2230,
                                             ISCO08 == "Paramedical practitioners" ~ 2240,
                                             ISCO08 == "Veterinarians" ~ 2250,
                                             ISCO08 == "Other health professionals" ~ 2260,
                                             ISCO08 == "Dentists" ~ 2261,
                                             ISCO08 == "Pharmacists" ~ 2262,
                                             ISCO08 == "Environmental & occupational health-hygiene professionals" ~ 2263,
                                             ISCO08 == "Physiotherapists" ~ 2264,
                                             ISCO08 == "Dieticians and nutritionists" ~ 2265,
                                             ISCO08 == "Audiologists and speech therapists" ~ 2266,
                                             ISCO08 == "Optometrists and ophthalmic opticians" ~ 2267,
                                             ISCO08 == "Health professionals not elsewhere classified" ~ 2269,
                                             ISCO08 == "Teaching professionals" ~ 2300,
                                             ISCO08 == "University and higher education teachers" ~ 2310,
                                             ISCO08 == "Vocational education teachers" ~ 2320,
                                             ISCO08 == "Secondary education teachers" ~ 2330,
                                             ISCO08 == "Primary school and early childhood teachers" ~ 2340,
                                             ISCO08 == "Primary school teachers" ~ 2341,
                                             ISCO08 == "Early childhood educators" ~ 2342,
                                             ISCO08 == "Other teaching professionals" ~ 2350,
                                             ISCO08 == "Education methods specialists" ~ 2351,
                                             ISCO08 == "Special needs teachers" ~ 2352,
                                             ISCO08 == "Other language teachers" ~ 2353,
                                             ISCO08 == "Other music teachers" ~ 2354,
                                             ISCO08 == "Other arts teachers" ~ 2355,
                                             ISCO08 == "Information technology trainers" ~ 2356,
                                             ISCO08 == "Teaching professionals not elsewhere classified" ~ 2359,
                                             ISCO08 == "Business and administration professionals" ~ 2400,
                                             ISCO08 == "Finance professionals" ~ 2410,
                                             ISCO08 == "Accountants" ~ 2411,
                                             ISCO08 == "Financial and investment advisers" ~ 2412,
                                             ISCO08 == "Financial analysts" ~ 2413,
                                             ISCO08 == "Administration professionals" ~ 2420,
                                             ISCO08 == "Management and organization analysts" ~ 2421,
                                             ISCO08 == "Policy administration professionals" ~ 2422,
                                             ISCO08 == "Personnel and careers professionals" ~ 2423,
                                             ISCO08 == "Training and staff development professionals" ~ 2424,
                                             ISCO08 == "Sales, marketing and public relations professionals" ~ 2430,
                                             ISCO08 == "Advertising and marketing professionals" ~ 2431,
                                             ISCO08 == "Public relations professionals" ~ 2432,
                                             ISCO08 == "Technical and medical sales professionals [excluding ICT]" ~ 2433,
                                             ISCO08 == "ICT sales professionals" ~ 2434,
                                             ISCO08 == "ICT professionals" ~ 2500,
                                             ISCO08 == "Software and applications developers and analysts" ~ 2510,
                                             ISCO08 == "Systems analysts" ~ 2511,
                                             ISCO08 == "Software developers" ~ 2512,
                                             ISCO08 == "Web and multimedia developers" ~ 2513,
                                             ISCO08 == "Applications programmers" ~ 2514,
                                             ISCO08 == "Software and applications developers and analysts not elsewhere classified" ~ 2519,
                                             ISCO08 == "Database and network professionals" ~ 2520,
                                             ISCO08 == "Database designers and administrators" ~ 2521,
                                             ISCO08 == "Systems administrators" ~ 2522,
                                             ISCO08 == "Computer network professionals" ~ 2523,
                                             ISCO08 == "Database and network professionals not elsewhere classified" ~ 2529,
                                             ISCO08 == "Legal, social and cultural professionals" ~ 2600,
                                             ISCO08 == "Legal professionals" ~ 2610,
                                             ISCO08 == "Lawyers" ~ 2611,
                                             ISCO08 == "Judges" ~ 2612,
                                             ISCO08 == "Legal professionals not elsewhere classified" ~ 2619,
                                             ISCO08 == "Librarians, archivists and curators" ~ 2620,
                                             ISCO08 == "Archivists and curators" ~ 2621,
                                             ISCO08 == "Librarians and related information professionals" ~ 2622,
                                             ISCO08 == "Social and religious professionals" ~ 2630,
                                             ISCO08 == "Economists" ~ 2631,
                                             ISCO08 == "Sociologists, anthropologists and related professionals" ~ 2632,
                                             ISCO08 == "Philosophers, historians and political scientists" ~ 2633,
                                             ISCO08 == "Psychologists" ~ 2634,
                                             ISCO08 == "Social work and counselling professionals" ~ 2635,
                                             ISCO08 == "Religious professionals" ~ 2636,
                                             ISCO08 == "Authors, journalists and linguists" ~ 2640,
                                             ISCO08 == "Authors and related writers" ~ 2641,
                                             ISCO08 == "Journalists" ~ 2642,
                                             ISCO08 == "Translators, interpreters and other linguists" ~ 2643,
                                             ISCO08 == "Creative and performing artists" ~ 2650,
                                             ISCO08 == "Visual artists" ~ 2651,
                                             ISCO08 == "Musicians, singers and composers" ~ 2652,
                                             ISCO08 == "Dancers and choreographers" ~ 2653,
                                             ISCO08 == "Film, stage and related directors and producers" ~ 2654,
                                             ISCO08 == "Actors" ~ 2655,
                                             ISCO08 == "Announcers on radio, television and other media" ~ 2656,
                                             ISCO08 == "Creative and performing artists not elsewhere classified" ~ 2659,
                                             ISCO08 == "Technicians and associate professionals" ~ 3000,
                                             ISCO08 == "Science and engineering associate professionals" ~ 3100,
                                             ISCO08 == "Physical and engineering science technicians" ~ 3110,
                                             ISCO08 == "Chemical and physical science technicians" ~ 3111,
                                             ISCO08 == "Civil engineering technicians" ~ 3112,
                                             ISCO08 == "Electrical engineering technicians" ~ 3113,
                                             ISCO08 == "Electronics engineering technicians" ~ 3114,
                                             ISCO08 == "Mechanical engineering technicians" ~ 3115,
                                             ISCO08 == "Chemical engineering technicians" ~ 3116,
                                             ISCO08 == "Mining and metallurgical technicians" ~ 3117,
                                             ISCO08 == "Draughtspersons" ~ 3118,
                                             ISCO08 == "Physical and engineering science technicians not elsewhere classified" ~ 3119,
                                             ISCO08 == "Mining, manufacturing and construction supervisors" ~ 3120,
                                             ISCO08 == "Mining supervisors" ~ 3121,
                                             ISCO08 == "Manufacturing supervisors" ~ 3122,
                                             ISCO08 == "Construction supervisors" ~ 3123,
                                             ISCO08 == "Process control technicians" ~ 3130,
                                             ISCO08 == "Power production plant operators" ~ 3131,
                                             ISCO08 == "Incinerator and water treatment plant operators" ~ 3132,
                                             ISCO08 == "Chemical processing plant controllers" ~ 3133,
                                             ISCO08 == "Petroleum and natural gas refining plant operators" ~ 3134,
                                             ISCO08 == "Metal production process controllers" ~ 3135,
                                             ISCO08 == "Process control technicians not elsewhere classified" ~ 3139,
                                             ISCO08 == "Life science technicians and related associate professionals" ~ 3140,
                                             ISCO08 == "Life science technicians [excluding medical]" ~ 3141,
                                             ISCO08 == "Agricultural technicians" ~ 3142,
                                             ISCO08 == "Forestry technicians" ~ 3143,
                                             ISCO08 == "Ship and aircraft controllers and technicians" ~ 3150,
                                             ISCO08 == "Ships engineers" ~ 3151,
                                             ISCO08 == "Ships deck officers and pilots" ~ 3152,
                                             ISCO08 == "Aircraft pilots and related associate professionals" ~ 3153,
                                             ISCO08 == "Air traffic controllers" ~ 3154,
                                             ISCO08 == "Air traffic safety electronics technicians" ~ 3155,
                                             ISCO08 == "Health associate professionals" ~ 3200,
                                             ISCO08 == "Medical and pharmaceutical technicians" ~ 3210,
                                             ISCO08 == "Medical imaging and therapeutic equipment technicians" ~ 3211,
                                             ISCO08 == "Medical and pathology laboratory technicians" ~ 3212,
                                             ISCO08 == "Pharmaceutical technicians and assistants" ~ 3213,
                                             ISCO08 == "Medical and dental prosthetic technicians" ~ 3214,
                                             ISCO08 == "Nursing and midwifery associate professionals" ~ 3220,
                                             ISCO08 == "Nursing associate professionals" ~ 3221,
                                             ISCO08 == "Midwifery associate professionals" ~ 3222,
                                             ISCO08 == "Traditional-complementary medicine assoc professionals" ~ 3230,
                                             ISCO08 == "Veterinary technicians and assistants" ~ 3240,
                                             ISCO08 == "Other health associate professionals" ~ 3250,
                                             ISCO08 == "Dental assistants and therapists" ~ 3251,
                                             ISCO08 == "Medical records and health information technicians" ~ 3252,
                                             ISCO08 == "Community health workers" ~ 3253,
                                             ISCO08 == "Dispensing opticians" ~ 3254,
                                             ISCO08 == "Physiotherapy technicians and assistants" ~ 3255,
                                             ISCO08 == "Medical assistants" ~ 3256,
                                             ISCO08 == "Environmental-occupational health inspectors etc" ~ 3257,
                                             ISCO08 == "Ambulance workers" ~ 3258,
                                             ISCO08 == "Health associate professionals not elsewhere classified" ~ 3259,
                                             ISCO08 == "Business and administration associate professionals" ~ 3300,
                                             ISCO08 == "Financial and mathematical associate professionals" ~ 3310,
                                             ISCO08 == "Securities and finance dealers and brokers" ~ 3311,
                                             ISCO08 == "Credit and loans officers" ~ 3312,
                                             ISCO08 == "Accounting associate professionals" ~ 3313,
                                             ISCO08 == "Statistical, mathematical and related associate professionals" ~ 3314,
                                             ISCO08 == "Valuers and loss assessors" ~ 3315,
                                             ISCO08 == "Sales and purchasing agents and brokers" ~ 3320,
                                             ISCO08 == "Insurance representatives" ~ 3321,
                                             ISCO08 == "Commercial sales representatives" ~ 3322,
                                             ISCO08 == "Buyers" ~ 3323,
                                             ISCO08 == "Trade brokers" ~ 3324,
                                             ISCO08 == "Business services agents" ~ 3330,
                                             ISCO08 == "Clearing and forwarding agents" ~ 3331,
                                             ISCO08 == "Conference and event planners" ~ 3332,
                                             ISCO08 == "Employment agents and contractors" ~ 3333,
                                             ISCO08 == "Real estate agents and property managers" ~ 3334,
                                             ISCO08 == "Business services agents not elsewhere classified" ~ 3339,
                                             ISCO08 == "Administrative and specialized secretaries" ~ 3340,
                                             ISCO08 == "Office supervisors" ~ 3341,
                                             ISCO08 == "Legal secretaries" ~ 3342,
                                             ISCO08 == "Administrative and executive secretaries" ~ 3343,
                                             ISCO08 == "Medical secretaries" ~ 3344,
                                             ISCO08 == "Regulatory government associate professionals" ~ 3350,
                                             ISCO08 == "Customs and border inspectors" ~ 3351,
                                             ISCO08 == "Government tax and excise officials" ~ 3352,
                                             ISCO08 == "Government social benefits officials" ~ 3353,
                                             ISCO08 == "Government licensing officials" ~ 3354,
                                             ISCO08 == "Police inspectors and detectives" ~ 3355,
                                             ISCO08 == "Regulatory government associate professionals not elsewhere classified" ~ 3359,
                                             ISCO08 == "Legal, social, cultural and related associate professionals" ~ 3400,
                                             ISCO08 == "Legal, social and religious associate professionals" ~ 3410,
                                             ISCO08 == "Legal and related associate professionals" ~ 3411,
                                             ISCO08 == "Social work associate professionals" ~ 3412,
                                             ISCO08 == "Religious associate professionals" ~ 3413,
                                             ISCO08 == "Sports and fitness workers" ~ 3420,
                                             ISCO08 == "Athletes and sports players" ~ 3421,
                                             ISCO08 == "Sports coaches, instructors and officials" ~ 3422,
                                             ISCO08 == "Fitness and recreation instructors and program leaders" ~ 3423,
                                             ISCO08 == "Artistic, cultural and culinary associate professionals" ~ 3430,
                                             ISCO08 == "Photographers" ~ 3431,
                                             ISCO08 == "Interior designers and decorators" ~ 3432,
                                             ISCO08 == "Gallery, museum and library technicians" ~ 3433,
                                             ISCO08 == "Chefs" ~ 3434,
                                             ISCO08 == "Other artistic and cultural associate professionals" ~ 3435,
                                             ISCO08 == "Information and communications technicians" ~ 3500,
                                             ISCO08 == "ICT operations and user support technicians" ~ 3510,
                                             ISCO08 == "ICT operations technicians" ~ 3511,
                                             ISCO08 == "ICT user support technicians" ~ 3512,
                                             ISCO08 == "Computer network and systems technicians" ~ 3513,
                                             ISCO08 == "Web technicians" ~ 3514,
                                             ISCO08 == "Telecommunications and broadcasting technicians" ~ 3520,
                                             ISCO08 == "Broadcasting and audio-visual technicians" ~ 3521,
                                             ISCO08 == "Telecommunications engineering technicians" ~ 3522,
                                             ISCO08 == "Clerical support workers" ~ 4000,
                                             ISCO08 == "General and keyboard clerks" ~ 4100,
                                             ISCO08 == "General office clerks" ~ 4110,
                                             ISCO08 == "Secretaries (general)" ~ 4120,
                                             ISCO08 == "Keyboard operators" ~ 4130,
                                             ISCO08 == "Typists and word processing operators" ~ 4131,
                                             ISCO08 == "Data entry clerks" ~ 4132,
                                             ISCO08 == "Customer services clerks" ~ 4200,
                                             ISCO08 == "Tellers, money collectors and related clerks" ~ 4210,
                                             ISCO08 == "Bank tellers and related clerks" ~ 4211,
                                             ISCO08 == "Bookmakers, croupiers and related gaming workers" ~ 4212,
                                             ISCO08 == "Pawnbrokers and money-lenders" ~ 4213,
                                             ISCO08 == "Debt-collectors and related workers" ~ 4214,
                                             ISCO08 == "Client information workers" ~ 4220,
                                             ISCO08 == "Travel consultants and clerks" ~ 4221,
                                             ISCO08 == "Contact centre information clerks" ~ 4222,
                                             ISCO08 == "Telephone switchboard operators" ~ 4223,
                                             ISCO08 == "Hotel receptionists" ~ 4224,
                                             ISCO08 == "Enquiry clerks" ~ 4225,
                                             ISCO08 == "Receptionists [general]" ~ 4226,
                                             ISCO08 == "Survey and market research interviewers" ~ 4227,
                                             ISCO08 == "Client information workers not elsewhere classified" ~ 4229,
                                             ISCO08 == "Numerical and material recording clerks" ~ 4300,
                                             ISCO08 == "Numerical clerks" ~ 4310,
                                             ISCO08 == "Accounting and bookkeeping clerks" ~ 4311,
                                             ISCO08 == "Statistical, finance and insurance clerks" ~ 4312,
                                             ISCO08 == "Payroll clerks" ~ 4313,
                                             ISCO08 == "Material-recording and transport clerks" ~ 4320,
                                             ISCO08 == "Stock clerks" ~ 4321,
                                             ISCO08 == "Production clerks" ~ 4322,
                                             ISCO08 == "Transport clerks" ~ 4323,
                                             ISCO08 == "Other clerical support workers" ~ 4400,
                                             ISCO08 == "Other clerical support workers" ~ 4410,
                                             ISCO08 == "Library clerks" ~ 4411,
                                             ISCO08 == "Mail carriers and sorting clerks" ~ 4412,
                                             ISCO08 == "Coding, proof-reading and related clerks" ~ 4413,
                                             ISCO08 == "Scribes and related workers" ~ 4414,
                                             ISCO08 == "Filing and copying clerks" ~ 4415,
                                             ISCO08 == "Personnel clerks" ~ 4416,
                                             ISCO08 == "Clerical support workers not elsewhere classified" ~ 4419,
                                             ISCO08 == "Service and sales workers" ~ 5000,
                                             ISCO08 == "Personal service workers" ~ 5100,
                                             ISCO08 == "Travel attendants, conductors and guides" ~ 5110,
                                             ISCO08 == "Travel attendants and travel stewards" ~ 5111,
                                             ISCO08 == "Transport conductors" ~ 5112,
                                             ISCO08 == "Travel guides" ~ 5113,
                                             ISCO08 == "Cooks" ~ 5120,
                                             ISCO08 == "Waiters and bartenders" ~ 5130,
                                             ISCO08 == "Waiters" ~ 5131,
                                             ISCO08 == "Bartenders" ~ 5132,
                                             ISCO08 == "Hairdressers, beauticians and related workers" ~ 5140,
                                             ISCO08 == "Hairdressers" ~ 5141,
                                             ISCO08 == "Beauticians and related workers" ~ 5142,
                                             ISCO08 == "Building and housekeeping supervisors" ~ 5150,
                                             ISCO08 == "Cleaning and housekeeping supervisors in offices, hotels etc" ~ 5151,
                                             ISCO08 == "Domestic housekeepers" ~ 5152,
                                             ISCO08 == "Building caretakers" ~ 5153,
                                             ISCO08 == "Other personal services workers" ~ 5160,
                                             ISCO08 == "Astrologers, fortune-tellers and related workers" ~ 5161,
                                             ISCO08 == "Companions and valets" ~ 5162,
                                             ISCO08 == "Undertakers and embalmers" ~ 5163,
                                             ISCO08 == "Pet groomers and animal care workers" ~ 5164,
                                             ISCO08 == "Driving instructors" ~ 5165,
                                             ISCO08 == "Personal services workers not elsewhere classified" ~ 5169,
                                             ISCO08 == "Sales workers" ~ 5200,
                                             ISCO08 == "Street and market salespersons" ~ 5210,
                                             ISCO08 == "Stall and market salespersons" ~ 5211,
                                             ISCO08 == "Street food salespersons" ~ 5212,
                                             ISCO08 == "Shop salespersons" ~ 5220,
                                             ISCO08 == "Shop keepers" ~ 5221,
                                             ISCO08 == "Shop supervisors" ~ 5222,
                                             ISCO08 == "Shop sales assistants" ~ 5223,
                                             ISCO08 == "Cashiers and ticket clerks" ~ 5230,
                                             ISCO08 == "Other sales workers" ~ 5240,
                                             ISCO08 == "Fashion and other models" ~ 5241,
                                             ISCO08 == "Sales demonstrators" ~ 5242,
                                             ISCO08 == "Door to door salespersons" ~ 5243,
                                             ISCO08 == "Contact centre salespersons" ~ 5244,
                                             ISCO08 == "Service station attendants" ~ 5245,
                                             ISCO08 == "Food service counter attendants" ~ 5246,
                                             ISCO08 == "Sales workers not elsewhere classified" ~ 5249,
                                             ISCO08 == "Personal care workers" ~ 5300,
                                             ISCO08 == "Child care workers and teachers aides" ~ 5310,
                                             ISCO08 == "Child care workers" ~ 5311,
                                             ISCO08 == "Teachers aides" ~ 5312,
                                             ISCO08 == "Personal care workers in health services" ~ 5320,
                                             ISCO08 == "Health care assistants" ~ 5321,
                                             ISCO08 == "Home-based personal care workers" ~ 5322,
                                             ISCO08 == "Personal care workers in health services not elsewhere classified" ~ 5329,
                                             ISCO08 == "Protective services workers" ~ 5400,
                                             ISCO08 == "Protective services workers" ~ 5410,
                                             ISCO08 == "Fire-fighters" ~ 5411,
                                             ISCO08 == "Police officers" ~ 5412,
                                             ISCO08 == "Prison guards" ~ 5413,
                                             ISCO08 == "Security guards" ~ 5414,
                                             ISCO08 == "Protective services workers not elsewhere classified" ~ 5419,
                                             ISCO08 == "Skilled agricultural, forestry and fishery workers" ~ 6000,
                                             ISCO08 == "Market-oriented skilled agricultural workers" ~ 6100,
                                             ISCO08 == "Market gardeners and crop growers" ~ 6110,
                                             ISCO08 == "Field crop and vegetable growers" ~ 6111,
                                             ISCO08 == "Tree and shrub crop growers" ~ 6112,
                                             ISCO08 == "Gardeners, horticultural and nursery growers" ~ 6113,
                                             ISCO08 == "Mixed crop growers" ~ 6114,
                                             ISCO08 == "Animal producers" ~ 6120,
                                             ISCO08 == "Livestock and dairy producers" ~ 6121,
                                             ISCO08 == "Poultry producers" ~ 6122,
                                             ISCO08 == "Apiarists and sericulturists" ~ 6123,
                                             ISCO08 == "Animal producers not elsewhere classified" ~ 6129,
                                             ISCO08 == "Mixed crop and animal producers" ~ 6130,
                                             ISCO08 == "Market-oriented skilled forestry, fishery, hunting workers" ~ 6200,
                                             ISCO08 == "Forestry and related workers" ~ 6210,
                                             ISCO08 == "Fishery workers, hunters and trappers" ~ 6220,
                                             ISCO08 == "Aquaculture workers" ~ 6221,
                                             ISCO08 == "Inland and coastal waters fishery workers" ~ 6222,
                                             ISCO08 == "Deep-sea fishery workers" ~ 6223,
                                             ISCO08 == "Hunters and trappers" ~ 6224,
                                             ISCO08 == "Subsistence farmers, fishers, hunters and gatherers" ~ 6300,
                                             ISCO08 == "Subsistence crop farmers" ~ 6310,
                                             ISCO08 == "Subsistence livestock farmers" ~ 6320,
                                             ISCO08 == "Subsistence mixed crop and livestock farmers" ~ 6330,
                                             ISCO08 == "Subsistence fishers, hunters, trappers and gatherers" ~ 6340,
                                             ISCO08 == "Craft and related trades workers" ~ 7000,
                                             ISCO08 == "Building and related trades workers, excluding electricians" ~ 7100,
                                             ISCO08 == "Building frame and related trades workers" ~ 7110,
                                             ISCO08 == "House builders" ~ 7111,
                                             ISCO08 == "Bricklayers and related workers" ~ 7112,
                                             ISCO08 == "Stonemasons, stone cutters, splitters and carvers" ~ 7113,
                                             ISCO08 == "Concrete placers, concrete finishers and related workers" ~ 7114,
                                             ISCO08 == "Carpenters and joiners" ~ 7115,
                                             ISCO08 == "Building frame and related trades workers not elsewhere classified" ~ 7119,
                                             ISCO08 == "Building finishers and related trades workers" ~ 7120,
                                             ISCO08 == "Roofers" ~ 7121,
                                             ISCO08 == "Floor layers and tile setters" ~ 7122,
                                             ISCO08 == "Plasterers" ~ 7123,
                                             ISCO08 == "Insulation workers" ~ 7124,
                                             ISCO08 == "Glaziers" ~ 7125,
                                             ISCO08 == "Plumbers and pipe fitters" ~ 7126,
                                             ISCO08 == "Air conditioning and refrigeration mechanics" ~ 7127,
                                             ISCO08 == "Painters, building structure cleaners and related trades workers" ~ 7130,
                                             ISCO08 == "Painters and related workers" ~ 7131,
                                             ISCO08 == "Spray painters and varnishers" ~ 7132,
                                             ISCO08 == "Building structure cleaners" ~ 7133,
                                             ISCO08 == "Metal, machinery and related trades workers" ~ 7200,
                                             ISCO08 == "Sheet-structural metal wekrs, moulders and welders, and related workers" ~ 7210,
                                             ISCO08 == "Metal moulders and coremakers" ~ 7211,
                                             ISCO08 == "Welders and flamecutters" ~ 7212,
                                             ISCO08 == "Sheet-metal workers" ~ 7213,
                                             ISCO08 == "Structural-metal preparers and erectors" ~ 7214,
                                             ISCO08 == "Riggers and cable splicers" ~ 7215,
                                             ISCO08 == "Blacksmiths, toolmakers and related trades workers" ~ 7220,
                                             ISCO08 == "Blacksmiths, hammersmiths and forging press workers" ~ 7221,
                                             ISCO08 == "Toolmakers and related workers" ~ 7222,
                                             ISCO08 == "Metal working machine tool setters and operators" ~ 7223,
                                             ISCO08 == "Metal polishers, wheel grinders and tool sharpeners" ~ 7224,
                                             ISCO08 == "Machinery mechanics and repairers" ~ 7230,
                                             ISCO08 == "Motor vehicle mechanics and repairers" ~ 7231,
                                             ISCO08 == "Aircraft engine mechanics and repairers" ~ 7232,
                                             ISCO08 == "Agricultural-industrial machinery mechanics & repairers" ~ 7233,
                                             ISCO08 == "Bicycle and related repairers" ~ 7234,
                                             ISCO08 == "Handicraft and printing workers" ~ 7300,
                                             ISCO08 == "Handicraft workers" ~ 7310,
                                             ISCO08 == "Precision-instrument makers and repairers" ~ 7311,
                                             ISCO08 == "Musical instrument makers and tuners" ~ 7312,
                                             ISCO08 == "Jewellery and precious-metal workers" ~ 7313,
                                             ISCO08 == "Potters and related workers" ~ 7314,
                                             ISCO08 == "Glass makers, cutters, grinders and finishers" ~ 7315,
                                             ISCO08 == "Sign writers, decorative painters, engravers and etchers" ~ 7316,
                                             ISCO08 == "Handicraft workers in wood, basketry and related materials" ~ 7317,
                                             ISCO08 == "Handicraft workers in textile, leather and related materials" ~ 7318,
                                             ISCO08 == "Handicraft workers not elsewhere classified" ~ 7319,
                                             ISCO08 == "Printing trades workers" ~ 7320,
                                             ISCO08 == "Pre-press technicians" ~ 7321,
                                             ISCO08 == "Printers" ~ 7322,
                                             ISCO08 == "Print finishing and binding workers" ~ 7323,
                                             ISCO08 == "Electrical and electronic trades workers" ~ 7400,
                                             ISCO08 == "Electrical equipment installers and repairers" ~ 7410,
                                             ISCO08 == "Building and related electricians" ~ 7411,
                                             ISCO08 == "Electrical mechanics and fitters" ~ 7412,
                                             ISCO08 == "Electrical line installers and repairers" ~ 7413,
                                             ISCO08 == "Electronics and telecommunications installers and repairers" ~ 7420,
                                             ISCO08 == "Electronics mechanics and servicers" ~ 7421,
                                             ISCO08 == "ICT installers and servicers" ~ 7422,
                                             ISCO08 == "Food processing, wood working, garment and related craft-trades wrks" ~ 7500,
                                             ISCO08 == "Food processing and related trades workers" ~ 7510,
                                             ISCO08 == "Butchers, fishmongers and related food preparers" ~ 7511,
                                             ISCO08 == "Bakers, pastry-cooks and confectionery makers" ~ 7512,
                                             ISCO08 == "Dairy-products makers" ~ 7513,
                                             ISCO08 == "Fruit, vegetable and related preservers" ~ 7514,
                                             ISCO08 == "Food and beverage tasters and graders" ~ 7515,
                                             ISCO08 == "Tobacco preparers and tobacco products makers" ~ 7516,
                                             ISCO08 == "Wood treaters, cabinet-makers and related trades workers" ~ 7520,
                                             ISCO08 == "Wood treaters" ~ 7521,
                                             ISCO08 == "Cabinet-makers and related workers" ~ 7522,
                                             ISCO08 == "Woodworking-machine tool setters and operators" ~ 7523,
                                             ISCO08 == "Garment and related trades workers" ~ 7530,
                                             ISCO08 == "Tailors, dressmakers, furriers and hatters" ~ 7531,
                                             ISCO08 == "Garment and related pattern-makers and cutters" ~ 7532,
                                             ISCO08 == "Sewing, embroidery and related workers" ~ 7533,
                                             ISCO08 == "Upholsterers and related workers" ~ 7534,
                                             ISCO08 == "Pelt dressers, tanners and fellmongers" ~ 7535,
                                             ISCO08 == "Shoemakers and related workers" ~ 7536,
                                             ISCO08 == "Other craft and related workers" ~ 7540,
                                             ISCO08 == "Underwater divers" ~ 7541,
                                             ISCO08 == "Shotfirers and blasters" ~ 7542,
                                             ISCO08 == "Product graders and testers [excluding foods and beverages]" ~ 7543,
                                             ISCO08 == "Fumigators and other pest and weed controllers" ~ 7544,
                                             ISCO08 == "Craft and related workers not elsewhere classified" ~ 7549,
                                             ISCO08 == "Plant and machine operators, and assemblers" ~ 8000,
                                             ISCO08 == "Stationary plant and machine operators" ~ 8100,
                                             ISCO08 == "Mining and mineral processing plant operators" ~ 8110,
                                             ISCO08 == "Miners and quarriers" ~ 8111,
                                             ISCO08 == "Mineral and stone processing plant operators" ~ 8112,
                                             ISCO08 == "Well drillers and borers and related workers" ~ 8113,
                                             ISCO08 == "Cement, stone and other mineral products machine operators" ~ 8114,
                                             ISCO08 == "Metal processing and finishing plant operators" ~ 8120,
                                             ISCO08 == "Metal processing plant operators" ~ 8121,
                                             ISCO08 == "Metal finishing, plating and coating machine operators" ~ 8122,
                                             ISCO08 == "Chemical-photograph products plant and machine operators" ~ 8130,
                                             ISCO08 == "Chemical products plant and machine operators" ~ 8131,
                                             ISCO08 == "Photographic products machine operators" ~ 8132,
                                             ISCO08 == "Rubber, plastic and paper products machine operators" ~ 8140,
                                             ISCO08 == "Rubber products machine operators" ~ 8141,
                                             ISCO08 == "Plastic products machine operators" ~ 8142,
                                             ISCO08 == "Paper products machine operators" ~ 8143,
                                             ISCO08 == "Textile, fur and leather products machine operators" ~ 8150,
                                             ISCO08 == "Fibre preparing, spinning and winding machine operators" ~ 8151,
                                             ISCO08 == "Weaving and knitting machine operators" ~ 8152,
                                             ISCO08 == "Sewing machine operators" ~ 8153,
                                             ISCO08 == "Bleaching, dyeing and fabric cleaning machine operators" ~ 8154,
                                             ISCO08 == "Fur and leather preparing machine operators" ~ 8155,
                                             ISCO08 == "Shoemaking and related machine operators" ~ 8156,
                                             ISCO08 == "Laundry machine operators" ~ 8157,
                                             ISCO08 == "Textile, fur and leather products machine operators not elsewhere classified" ~ 8159,
                                             ISCO08 == "Food and related products machine operators" ~ 8160,
                                             ISCO08 == "Wood processing and papermaking plant operators" ~ 8170,
                                             ISCO08 == "Pulp and papermaking plant operators" ~ 8171,
                                             ISCO08 == "Wood processing plant operators" ~ 8172,
                                             ISCO08 == "Other stationary plant and machine operators" ~ 8180,
                                             ISCO08 == "Glass and ceramics plant operators" ~ 8181,
                                             ISCO08 == "Steam engine and boiler operators" ~ 8182,
                                             ISCO08 == "Packing, bottling and labelling machine operators" ~ 8183,
                                             ISCO08 == "Stationary plant and machine operators not elsewhere classified" ~ 8189,
                                             ISCO08 == "Assemblers" ~ 8200,
                                             ISCO08 == "Assemblers" ~ 8210,
                                             ISCO08 == "Mechanical machinery assemblers" ~ 8211,
                                             ISCO08 == "Electrical and electronic equipment assemblers" ~ 8212,
                                             ISCO08 == "Assemblers not elsewhere classified" ~ 8219,
                                             ISCO08 == "Drivers and mobile plant operators" ~ 8300,
                                             ISCO08 == "Locomotive engine drivers and related workers" ~ 8310,
                                             ISCO08 == "Locomotive engine drivers" ~ 8311,
                                             ISCO08 == "Railway brake, signal and switch operators" ~ 8312,
                                             ISCO08 == "Car, van and motorcycle drivers" ~ 8320,
                                             ISCO08 == "Motorcycle drivers" ~ 8321,
                                             ISCO08 == "Car, taxi and van drivers" ~ 8322,
                                             ISCO08 == "Heavy truck and bus drivers" ~ 8330,
                                             ISCO08 == "Bus and tram drivers" ~ 8331,
                                             ISCO08 == "Heavy truck and lorry drivers" ~ 8332,
                                             ISCO08 == "Mobile plant operators" ~ 8340,
                                             ISCO08 == "Mobile farm and forestry plant operators" ~ 8341,
                                             ISCO08 == "Earthmoving and related plant operators" ~ 8342,
                                             ISCO08 == "Crane, hoist and related plant operators" ~ 8343,
                                             ISCO08 == "Lifting truck operators" ~ 8344,
                                             ISCO08 == "Ships deck crews and related workers" ~ 8350,
                                             ISCO08 == "Elementary occupations" ~ 9000,
                                             ISCO08 == "Cleaners and helpers" ~ 9100,
                                             ISCO08 == "Domestic, hotel and office cleaners and helpers" ~ 9110,
                                             ISCO08 == "Domestic cleaners and helpers" ~ 9111,
                                             ISCO08 == "Cleaners and helpers in offices, hotels etc" ~ 9112,
                                             ISCO08 == "Vehicle, window, laundry and other hand cleaning workers" ~ 9120,
                                             ISCO08 == "Hand launderers and pressers" ~ 9121,
                                             ISCO08 == "Vehicle cleaners" ~ 9122,
                                             ISCO08 == "Window cleaners" ~ 9123,
                                             ISCO08 == "Other cleaning workers" ~ 9129,
                                             ISCO08 == "Agricultural, forestry and fishery labourers" ~ 9200,
                                             ISCO08 == "Agricultural, forestry and fishery labourers" ~ 9210,
                                             ISCO08 == "Crop farm labourers" ~ 9211,
                                             ISCO08 == "Livestock farm labourers" ~ 9212,
                                             ISCO08 == "Mixed crop and livestock farm labourers" ~ 9213,
                                             ISCO08 == "Garden and horticultural labourers" ~ 9214,
                                             ISCO08 == "Forestry labourers" ~ 9215,
                                             ISCO08 == "Fishery and aquaculture labourers" ~ 9216,
                                             ISCO08 == "Labourers mining, construction, manufactur & transport" ~ 9300,
                                             ISCO08 == "Mining and construction labourers" ~ 9310,
                                             ISCO08 == "Mining and quarrying labourers" ~ 9311,
                                             ISCO08 == "Civil engineering labourers" ~ 9312,
                                             ISCO08 == "Building construction labourers" ~ 9313,
                                             ISCO08 == "Manufacturing labourers" ~ 9320,
                                             ISCO08 == "Hand packers" ~ 9321,
                                             ISCO08 == "Manufacturing labourers not elsewhere classified" ~ 9329,
                                             ISCO08 == "Transport and storage labourers" ~ 9330,
                                             ISCO08 == "Hand and pedal vehicle drivers" ~ 9331,
                                             ISCO08 == "Drivers of animal-drawn vehicles and machinery" ~ 9332,
                                             ISCO08 == "Freight handlers" ~ 9333,
                                             ISCO08 == "Shelf fillers" ~ 9334,
                                             ISCO08 == "Food preparation assistants" ~ 9400,
                                             ISCO08 == "Food preparation assistants" ~ 9410,
                                             ISCO08 == "Fast food preparers" ~ 9411,
                                             ISCO08 == "Kitchen helpers" ~ 9412,
                                             ISCO08 == "Street and related sales and service workers" ~ 9500,
                                             ISCO08 == "Street and related service workers" ~ 9510,
                                             ISCO08 == "Street vendors [excluding food]" ~ 9520,
                                             ISCO08 == "Refuse workers and other elementary workers" ~ 9600,
                                             ISCO08 == "Refuse workers" ~ 9610,
                                             ISCO08 == "Garbage and recycling collectors" ~ 9611,
                                             ISCO08 == "Refuse sorters" ~ 9612,
                                             ISCO08 == "Sweepers and related labourers" ~ 9613,
                                             ISCO08 == "Other elementary workers" ~ 9620,
                                             ISCO08 == "Messengers, package deliverers and luggage porters" ~ 9621,
                                             ISCO08 == "Odd job persons" ~ 9622,
                                             ISCO08 == "Meter readers and vending-machine collectors" ~ 9623,
                                             ISCO08 == "Water and firewood collectors" ~ 9624,
                                             ISCO08 == "Elementary workers not elsewhere classified~ " ~ 9629,
                                             # Add missing
                                             ISCO08 == "Production and specialised services managers" ~ 1321,
                                             ISCO08 == "Manufacturing, mining, construction, and distribution managers" ~ 1321,
                                             ISCO08 == "Information and communications technology service managers" ~ 1330,
                                             ISCO08 == "Engineering professionals (excluding electro technology)" ~ 3112,
                                             ISCO08 == "Environmental and occupational health and hygiene professionals" ~ 2263,
                                             ISCO08 == "Technical and medical sales professionals (excluding ICT)" ~ 2433,
                                             ISCO08 == "Information and communications technology sales professionals" ~ 2433,
                                             ISCO08 == "Information and communications technology professionals" ~ 1330,
                                             ISCO08 == "Life science technicians (excluding medical)" ~ 3141,
                                             ISCO08 == "Ships' engineers" ~ 3151,
                                             ISCO08 == "Ships' deck officers and pilots" ~ 3152,
                                             ISCO08 == "Traditional and complementary medicine associate professionals" ~ 2230,
                                             ISCO08 == "Environmental and occupational health inspectors and associates" ~ 3257,
                                             ISCO08 == "Administrative and specialised secretaries" ~ 3343,
                                             ISCO08 == "Information and communications technology operations and user support technicians" ~ 3512,
                                             ISCO08 == "Information and communications technology operations technicians" ~ 3512,
                                             ISCO08 == "Information and communications technology user support technicians" ~ 3512,
                                             ISCO08 == "Receptionists (general)" ~ 4226,
                                             ISCO08 == "Cleaning and housekeeping supervisors in offices, hotels and other establishments" ~ 5151,
                                             ISCO08 == "Teachers' aides" ~ 2352,
                                             ISCO08 == "Agricultural and industrial machinery mechanics and repairers" ~ 7233,
                                             ISCO08 == "Information and communications technology installers and servicers" ~ 3512,
                                             ISCO08 == "Food processing, wood working, garment and other craft and related trades workers" ~ 7318,
                                             ISCO08 == "Product graders and testers (excluding foods and beverages)" ~ 7543,
                                             ISCO08 == "Chemical and photographic products plant and machine operators" ~ 8132,
                                             ISCO08 == "Ships' deck crews and related workers" ~ 8350,
                                             ISCO08 == "Cleaners and helpers in offices, hotels and other establishments" ~ 9112,
                                             ISCO08 == "Labourers in mining, construction, manufacturing and transport" ~ 9311,
                                             ISCO08 == "Street vendors (excluding food)" ~ 5211,
                                             #ISCO08 == "Elementary workers not elsewhere classified" ~ ,
                                       )) 
  